# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/viterbi_v7_0.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==viterbi_v7_0 || ORIG_REF_NAME==viterbi_v7_0} -quiet] -quiet

# IP: C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/deinter_lut.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==deinter_lut || ORIG_REF_NAME==deinter_lut} -quiet] -quiet

# IP: ip/div_gen_xlslice_0_0/div_gen_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_xlslice_0_0 || ORIG_REF_NAME==div_gen_xlslice_0_0} -quiet] -quiet

# IP: C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/complex_multiplier.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complex_multiplier || ORIG_REF_NAME==complex_multiplier} -quiet] -quiet

# IP: C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/atan_lut.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==atan_lut || ORIG_REF_NAME==atan_lut} -quiet] -quiet

# IP: C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/rot_lut.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rot_lut || ORIG_REF_NAME==rot_lut} -quiet] -quiet
