# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {HDL 9-3116}  -string {{CRITICAL WARNING: [HDL 9-3116] 'indexed name' is not a type [E:/Xilinx/Artix-7/Workspace-XC7A100T-DDR3-Wukong/08_1_hdmi_output_test/HDMI_output_test.srcs/sources_1/imports/src/TMDS_Encoder.vhd:90]}}  -suppress 
set_msg_config  -id {[Synth 8-7080]}  -severity {WARNING}  -new_severity {INFO} 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/sharjeel/Desktop/Viterbi/RX/RX.cache/wt [current_project]
set_property parent.project_path C:/Users/sharjeel/Desktop/Viterbi/RX/RX.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/sharjeel/Desktop/openofdm-master/openofdm-master/verilog/coregen/div_gen_new_ip_core_zynq [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/sharjeel/Desktop/Viterbi/RX/RX.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/sharjeel/Desktop/Viterbi/RX/RX.srcs/sources_1/imports/openofdm-master/ip_repo/atan_lut/atan_lut.coe
add_files C:/Users/sharjeel/Desktop/Viterbi/RX/RX.srcs/sources_1/imports/openofdm-master/ip_repo/deinter_lut/deinter_lut.coe
add_files C:/Users/sharjeel/Desktop/Viterbi/RX/RX.srcs/sources_1/imports/openofdm-master/ip_repo/rot_lut/rot_lut.coe
read_mem {
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/rot_lut.mif
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/atan_lut.mif
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/deinter_lut.mif
}
read_verilog -library xil_defaultlib {
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/bits_to_bytes.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/calc_mean.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/complex_mult.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/complex_to_mag.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/complex_to_mag_sq.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/crc32.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/deinterleave.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/delayT.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/common_defs.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/demodulate.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/descramble.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/div_gen.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/divider.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/openofdm_rx_pre_def.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/common_params.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/dot11.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/equalizer.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/fifo_sample_delay.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/ht_sig_crc.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/mv_avg.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/mv_avg_dual_ch.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/ofdm_decoder.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/phase.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/phy_len_calculation.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/power_trigger.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/usrp2/ram_2port.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/rot_lut/rot_lut.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/rotate.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/running_sum_dual_ch.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/signal_watchdog.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/stage_mult.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/sync_long.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/sync_short.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/openofdm_rx_git_rev.v
  C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/openofdm_rx.v
}
read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/viterbi_v7_0.xco

read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/deinter_lut.xco

read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/RX.srcs/sources_1/ip/div_gen_xlslice_0_0/div_gen_xlslice_0_0.xci

read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/complex_multiplier.xco

read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/atan_lut.xco

read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/verilog/coregen/rot_lut.xco

read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/RX.srcs/div_gen_div_gen_0_0/ip/div_gen_div_gen_0_0/div_gen_div_gen_0_0.xci

read_ip -quiet C:/Users/sharjeel/Desktop/Viterbi/RX/RX.srcs/xfft_v9/ip/xfft_v9/xfft_v9.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top openofdm_rx -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef openofdm_rx.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file openofdm_rx_utilization_synth.rpt -pb openofdm_rx_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
